### ISSUE TITLE
HeatPumps #81

### ISSUE THREAD

**Issue by follox** [persandstrom/python-verisure#102]
The python script here:
https://github.com/persandstrom/python-verisure/issues/81#issuecomment-424046082
Only showing one heatpump. I got two and really want both to show up. 
It is also missing quiet mode and econavi, but I am not sure if this is settings which shows in the Verisure app eiter. It is only on my remote control.

**Comment by niro1987** [comment]
close?

**Comment by persandstrom** [comment]
Yes
