### ISSUE TITLE
Feature request - Change Auto Lock settings for locks

### ISSUE THREAD

**Issue by lindehoff** [persandstrom/python-verisure#11]
It would be great if one could change the auto lock feature.
You can get the current staten state for the Auto Lock from: 
Get: https://mypages.verisure.com/settings/autorelock
Response: `{"doorLocks":[{"autoRelockEnabled":true,"deviceLabel":"xxxx xxxx","description":"SmartLock - Location"}]}`

To change the state:
Post: https://mypages.verisure.com/settings/setautorelock.cmd
Data:  `enabledDoorLocks={device Lable}&doorLockDevices%5B0%5D.autoRelockEnabled=true&_doorLockDevices%5B0%5D.autoRelockEnabled=on&_csrf={current csrf}`
Response: No response

**Comment by persandstrom** [comment]
Ok, i didn't know about this feature. Seem quite easy to add

**Comment by persandstrom** [comment]
The settings was a bit more different from overviews than I expected. Hopefully I'll get some time to look at it soon.

**Comment by persandstrom** [comment]
In #13 I have succeeded to set the location of a smartplug. I did this as a first step to understand how settings work. 

To be continued..

**Comment by persandstrom** [comment]
Done
