### ISSUE TITLE
Is there a way to know there is a firmware update ?

### ISSUE THREAD

**Issue by thomasgermain** [persandstrom/python-verisure#116]
Hello,

i'm trying to find a way to know when there is a firmware update.

I currently have a waiting update, but i'm not able to find anything related to an update in the API. I can only see my current firmware version with `vsure username pass installations`.

I think there is a way through the API since the android is able to tell me there is an update.

Do you know how can I achieve that ?

Thanks,

Thomas

**Comment by persandstrom** [comment]
Hi, 

Yes, it should be possible to get that information. I would need to capture the communication when that page is requested. I can look into that, when I get some time over. If you want to do that yourself you can set up a reverse proxy, like Charles and configure your phone to use that proxy (I have not got that to work with later version of android, so you might need to get hold of a phone that has not been updated for a few years)

**Comment by thomasgermain** [comment]
I already tried checking website request, but apparently the full html page is rendered server side.

I'm gonna try decompiling the android app.

Thanks for the tips, i'll let you know

**Comment by thomasgermain** [comment]
I came back to this feature request: I found a way to know if there is firmware update, (I checked from my pages website).

**POST** https://m-api01.verisure.com/graphql
- content-type: application/json
- Cookie: country=BE; language=fr; sEc.verisure=[redacted]; vid=[redacted]; username=[redacted]; vs-access=[redacted]

Payload:
```json
[{
      "operationName":"Firmware",
      "variables":{
         "giid":"93885169704"
      },
      "query":"query Firmware($giid: String!) {  installation(giid: $giid) {    firmware {      status {        latestFirmware        requestedFirmware        upgradeable        gateways {          reportedRunningFirmware}}}}}"
   }]
```

wich is giving this response:
```json
{
    "data": {
        "installation": {
            "firmware": {
                "status": {
                    "latestFirmware": 33310,
                    "requestedFirmware": 33260,
                    "upgradeable": true,
                    "gateways": [
                        {
                            "reportedRunningFirmware": 33260
                        }
                    ]
                }
            }
        }
    }
}
```

So I don't know if it can be included in this project since this is the graphql endpoint.

**Comment by persandstrom** [comment]
I have added a new command ```firmware_status```, the output will inform if the firmware is upgradable

**Comment by thomasgermain** [comment]
Works like a charm, thanks :)
