### ISSUE TITLE
Authentication issue for UK installation

### ISSUE THREAD

**Issue by bazwilliams** [persandstrom/python-verisure#119]
We've recently had a Verisure alarm installed in the UK. If I attempt to login using the same credentials required for the mobile app (My Verisure) I receive the following error:

```
Traceback (most recent call last):
  File "/Users/barry/Projects/venv/bin/vsure", line 11, in <module>
    load_entry_point('vsure==1.5.4', 'console_scripts', 'vsure')()
  File "/Users/barry/Projects/venv/lib/python3.7/site-packages/verisure/__main__.py", line 214, in main
    session.login()
  File "/Users/barry/Projects/venv/lib/python3.7/site-packages/verisure/session.py", line 90, in login
    self._create_cookie()
  File "/Users/barry/Projects/venv/lib/python3.7/site-packages/verisure/session.py", line 120, in _create_cookie
    raise ResponseError(response.status_code, response.text)
verisure.session.ResponseError: Invalid response, status code: 401 - Data: {"errorGroup":"UNAUTHORIZED","errorCode":"AUT_00004","errorMessage":"Invalid username/password/authentication method combination"}
```

I've tried with my email address and also with a secondary user account created within the app. I suspect the 'My Verisure' app is unfortunately using a different API.

**Comment by persandstrom** [comment]
I know that the script does not work for all regions, like Spain, that could be that case with UK as well. As you say, there seem to be one verisure API, and a securitas API.

**Comment by j-vizcaino** [comment]
Stumbled upon this today as well, trying to get the Verisure integration working with Home Assistant.
At least for french customers, the site does not use the `verisure.com` endpoint but some `securitasdirect.fr` endpoint.

**Comment by bazwilliams** [comment]
This version might work https://github.com/segalion/securitasdirect it seems verisure have a few different backend systems.

**Comment by nckslater** [comment]
I live in Spain and use the Verisure app. Thanks for this integration. I have the alarm panel working perfectly. Is there any plans to add the various sensors and cameras? Thanks
