### ISSUE TITLE
Error if location includes œøå 

### ISSUE THREAD

**Issue by tbergo** [persandstrom/python-verisure#12]
Get the following error if 'location' includes "œøå".

Traceback (most recent call last):
  File "verisure.py", line 127, in <module>
    print_overviews(verisure.__dict__[dev].get())
  File "verisure.py", line 17, in print_overviews
    print_overview(overview)
  File "verisure.py", line 26, in print_overview
    print('\t{}: {}'.format(key, value))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 6: ordinal not in range(128)

**Comment by persandstrom** [comment]
I will take a look at this. Thanks

**Comment by persandstrom** [comment]
My guess is that this is an issue with your terminal not being able to display the characters. 

if you open the terminal and type 'ø' and then enter, the response should be something like
```
[per@alarmpi python-verisure]$ ø
-bash: ø: kommandot finns inte
```
if the character is supported. 

If you get: 
```
[per@alarmpi python-verisure]$ ø 
-bash: $'\303\270': command not found
```
Then you have to change your "locale" setting. How to do that might depend on your system.

Please tell me if this solved the issue or if you need more help.

**Comment by tbergo** [comment]
I will look into it, and see if it's related to my terminal setting. Thanks.
