### ISSUE TITLE
API unavailable

### ISSUE THREAD

**Issue by PetrolHead2** [persandstrom/python-verisure#120]
Hi,
Since the update of the app the 8th of June it looks like Verisure have changed their API.
The Verisure My Pages seem to be using a new GraphQL API.
/PH

**Comment by persandstrom** [comment]
Hi, 
I have not noticed any problems yet and can still use the script. I'll keep an eye out but can't really do any development until it changes for me.

**Comment by krambriw** [comment]
Might be country/region specific. Still works perfect here for me in Sweden

**Comment by turbokongen** [comment]
Works good in Norway too:ok_hand:

**Comment by PetrolHead2** [comment]
Yes, it works fine!
Had to do a restart of home assistant and after that it works fine.
Just bad timing that is started to fail just after an upgrade of the app.
