### ISSUE TITLE
Is Verisure down or broken?

### ISSUE THREAD

**Issue by krambriw** [persandstrom/python-verisure#123]
Stopped working this morning. Is this also the case for you?

**Comment by persandstrom** [comment]
It's working for me, do you still experience this problem?

**Comment by krambriw** [comment]
I found the problem!!! They have changed the response to the session.get_overview(). Before the smart plugs where listed in overview['controlPlugs'] and now we find them in overview['smartPlugs']
My script is working again, your code is working fine, it was on my side when I wanted to get the statuses of all my smart plugs
