### ISSUE TITLE
Response from new auth URL's don't respond with cookie

### ISSUE THREAD

**Issue by ptz0n** [persandstrom/python-verisure#127]
Hi all, I'm maintaining the Node.js module and Homebridge plugin for Verisure and have identified problems with these new endpoints.

We receive a HTTP 200 response, but without the set-cookie header `vid`. As you know, this is the cookie we use to auth other requests.

So far, users in Belgium seem to be affected.

Have you seen or heard anything regarding this strange behavior?

**Comment by persandstrom** [comment]
Hi!

I have not had any reported issues on the new endpoints so far. Home-assistant is still using the old endpoints though and will update to the new ones on Wednesday. So if there are any issues for Belgian (or other) users I guess we will see some reports later this week.

**Comment by hoefs** [comment]
> Hi!
> 
> I have not had any reported issues on the new endpoints so far. Home-assistant is still using the old endpoints though and will update to the new ones on Wednesday. So if there are any issues for Belgian (or other) users I guess we will see some reports later this week.

https://github.com/ptz0n/homebridge-verisure/issues/101

Since last week, I am unable to use the plugin. Seems like the login procedure was altered.

**Comment by persandstrom** [comment]
@hoefs Take a look under settings in MyPages and see if there is any way to opt-out from two factor authentication, we have not yet had this update in Sweden

**Comment by hoefs** [comment]
> @hoefs Take a look under settings in MyPages and see if there is any way to opt-out from two factor authentication, we have not yet had this update in Sweden

I was searching last night in mypages, but couldn't find it, until now:
![verisure2](https://user-images.githubusercontent.com/7440522/109478346-6a6b9900-7a79-11eb-9a49-d3ae65cf39ea.png)

**Comment by persandstrom** [comment]
Great, glad to be of help
