### ISSUE TITLE
Error trying to use m-api

### ISSUE THREAD

**Issue by Soleg06** [persandstrom/python-verisure#133]
I'm trying to use the new m-api but I can't seem to log in,  what am I doing wrong??
I get these errormessages
 
LoginError: Failed to log in

AttributeError: 'Session' object has no attribute '_cookies'

Edit: Solved it! Needed to disable two factor authentication on my account. Got a totally different cookie now!

**Comment by persandstrom** [comment]
Sorry for the late reply, missed this one. Great that you solved it!
