### ISSUE TITLE
Documentation API

### ISSUE THREAD

**Issue by RosiersRobin** [persandstrom/python-verisure#135]
Hi,

Where could I find the API docs?

**Comment by persandstrom** [comment]
The is no more documentation than what you find in the readme, and the documentated methods in  python-verisure/verisure/session.py

**Comment by RosiersRobin** [comment]
I mean the API docs from verisure themself. How could you have built this otherwise?

**Comment by krambriw** [comment]
Reverse engineering my best guess!!

**Comment by persandstrom** [comment]
Yes, by recording the traffic to and from my phone

**Comment by RosiersRobin** [comment]
Poah, respect! Thakns for the info! :D
