### ISSUE TITLE
Verisure api is not working

### ISSUE THREAD

**Issue by crackers81** [persandstrom/python-verisure#160]
![FB_IMG_1678864083342](https://user-images.githubusercontent.com/47931705/225277329-f275c562-56e2-469d-9183-92b490190a4f.jpg)

**Comment by persandstrom** [comment]
Might be that verisure has closed down this api now. The solution would be to start using version-2 of python-verisure. This is homeassistant, right?

**Comment by krambriw** [comment]
version-2 ???

**Comment by persandstrom** [comment]
The branch version-2 (default branch). It uses the new graphql based API. Homeassistant still uses version-1, but @niro1987 is working on an updated plugin. More info in this discussion #138

**Comment by krambriw** [comment]
Alright, I had the older 1.8.1 version installed. Now with the 2.6.1 it is again able to login, also without mfa. BUT this newer version of sessions.py is unfortunately not backward compatible. In my home-made Python script (that is doing much more than just Verisure) I used get_overview() and this is not available anymore. I now have to make a rather huge re-design of my script :(

**Comment by krambriw** [comment]
Anyway, Per, thank you very much!! I have now sorted out things in my script, everything is back to normal in my case when using version-2
Best regards, Walter

**Comment by krambriw** [comment]
Just one more Q, I do experience an automatic logoff after approx 15 minutes. Is this expected?

**Comment by krambriw** [comment]
I guess I understand, the life time of the cookie is 15 minutes....
When this happen I just do a new login: session.login()
This seems to work fine

**Comment by persandstrom** [comment]
Have you tried to do update_cookie()?

**Comment by krambriw** [comment]
Thanks, just tried that, it seems to be enough, is working fine, no need to do new login
Maybe have a routin (in my case I consider a special thread) that updates the cookie let's say every ten minute, should let you be online all time
Best regards, Walter

**Comment by krambriw** [comment]
Worked fine. Separate thread in my python script, updating the cookie every 10 minute. My feeling is also that the command and response when operating smart plugs is faster with this api. Is it just me?

![Skärmavbild 2023-03-17 kl  09 20 26](https://user-images.githubusercontent.com/20238676/225851535-c69e2680-034e-46cd-b7f4-6790097c56c2.png)
