### ISSUE TITLE
Problem using login_cookie

### ISSUE THREAD

**Issue by mpadwick** [persandstrom/python-verisure#164]
Hi
I'm struggling to get my script to work. I want to use MFA login with cashed cookie. I have generated the cookie file but I'm not able to reference it successfully in my script.

```
import verisure

USERNAME = "user"
PASSWORD = "password"

session = verisure.Session(USERNAME, PASSWORD)
installations = session.login_cookie("./cookie")
```

The above code above gives me the error below.  I have tried merios ways of pointing to the file "./cookie" with no successes.
```
installations = session.login_cookie("./cookie")
TypeError: login_cookie() takes 1 positional argument but 2 were given
```

Any help would be much appreciated.

**Comment by persandstrom** [comment]
Hi,

The cookie path is passed to the Session constructor.

In ```__main__.py```, you can see how it is done for the CLI application.

```python
session = Session(username, password, cookie)

try:
    # try using the cookie first
    installations = session.login_cookie()
except LoginError:
    installations = None

```

**Comment by mpadwick** [comment]
Thanks, worked like a charm
