### ISSUE TITLE
/xbn/2/installation/' + giid + '/overview'

### ISSUE THREAD

**Issue by ClarreJu** [persandstrom/python-verisure#167]
Hi Per!

A bit of topic. 

I have implemented this in Goolge script to have it in the cloud. I have "stolen" a lot from you. Thank you!

I have previusly used ...'/xbn/2/installation/' + giid + '/overview' to get data from all the sensors. 

This is not supported any more. No I get: {"errorGroup":"NOT_IMPLEMENTED","errorCode":"VAL_01797","errorMessage":"This API is not supported anymore "}

Getting and setting armstate works finad and with the same API calls as before.

Any idea how to get the temperateure data now? What the API call looks like.

Tack på förhand!

All the best

C-H

**Comment by persandstrom** [comment]
Hi!

No shame in stealing :)

A lot have changed, take a look at the version-2 branch. 

/Per

**Comment by ClarreJu** [comment]
Thank you! Will dig into it!

All the best

C-H
