### ISSUE TITLE
Getting unicode errors...

### ISSUE THREAD

**Issue by Snille** [persandstrom/python-verisure#17]
Hi!
I'm getting: UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 10: ordinal not in range(128) when trying to receive the name (last person who armed/disarmed) of myPages.alarm.get() function.
My wife has an "ö" in her last name. :)

**Comment by lindehoff** [comment]
I think it's your terminal, have a look at this issue #12

**Comment by Snille** [comment]
Ah! Thank you. I had forgot to do "dpkg-reconfigure locales" on the new server. :)

**Comment by Snille** [comment]
Some more info if anyone else stumbles on this.
I'm running Ubuntu Server 14.04.3 (in an LXC environment).
If you get this problem it's probably a locale Issue.
More info here: https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue
This is want I did (with sudo if you are not root):
# echo 'LC_ALL="en_US.UTF-8"' | sudo tee -a /etc/default/locale
# echo 'LANG="en_US.UTF-8"' | sudo tee -a /etc/default/locale
# echo 'LANGUAGE="en_US:en"' | sudo tee -a /etc/default/locale
# locale-gen "en_US.UTF-8"
# dpkg-reconfigure locales
Then rebooted just for the fun of it.
Then it worked. :)

**Comment by persandstrom** [comment]
Thanks for the instructions! I'll add something in the exception message that will a bit clearer to the users.
