### ISSUE TITLE
504 when logging in with MFA

### ISSUE THREAD

**Issue by rasmusbe** [persandstrom/python-verisure#174]
Hi,

I'm getting 504 when I try to login with MFA via the CLI
`python -m verisure --mfa email@email.com password`
```
Invalid response, status code: 504 - Data: <html>
<head>
<title>Verisure APIGW</title>
</head>
<body>
<h1>Verisure API Gateway</h1>
<hr>
<p>Welcome to the Verisure API Gateway</p>
</body>
</html>
```

Update:
It seems like the cookie is set sucessfully and I can run other commands after that

**Comment by persandstrom** [comment]
Hi!

If you add a request for data in the same command it should work ```python -m verisure --mfa --smartplugs email@email.com password```. I will add a check so that no "empty" requests for are transmitted. 

The empty request seems to timeout after a while

**Comment by rasmusbe** [comment]
Thanks! I did misread the readme it seems 😄 
Maybe some kind of output like "Logged in" would be good if the request is empty, so no one else does the same mistake as me.
