### ISSUE TITLE
read password from env var or file instead of argument

### ISSUE THREAD

**Issue by hydrargyrum** [persandstrom/python-verisure#178]
giving passwords as command line arguments is insecure:
- it's stored in shell history
- any user running `ps` can see your password

it would be nice, as an alternative if password is not given, to read it from an env variable (`$VERISURE_PASSWORD`), from a file, and/or from TTY (use python standard lib `getpass.getpass()`) or stdin
i think TTY is choice number 1, easy to impl, env var or file comes next, your choice

**Comment by persandstrom** [comment]
I have added a prompt as suggested, password will be requested if you do not enter a password as input. You can, and could before this change, use environment variable if you want by passing it as an argument:
```bash
$ vsure $VERISURE_USER $VERISURE_PASSWORD --smart-button
```

**Comment by hydrargyrum** [comment]
thanks!
