### ISSUE TITLE
Get Devices

### ISSUE THREAD

**Issue by lindehoff** [persandstrom/python-verisure#2]
Is it possible to get a list of the different devices on MyPage?

**Comment by persandstrom** [comment]
Verisure has implemented so that they have one request for each device type and mypages.py reflects that. 

It would be quite easy to add a function that sends a request for each device type and returns a list of overviews. Is that what you need?

**Comment by lindehoff** [comment]
Yes that would be very helpfull. I'm trying to write a plugin for my Home Automation system.

**Comment by persandstrom** [comment]
I have added a new function ```get_overviews()```. It does not take any parameters and will read the status of all devices. 

May I ask which home automation system you are writing a plugin for?

**Comment by lindehoff** [comment]
That's truly amazing, thank you. The system I'm using is Indigo, http://www.indigodomo.com
When my plug in is done I will post it on GitHub and, of course, reference to this project which will be required to use my plugin.

**Comment by lindehoff** [comment]
It works great, I have now started my development of the plug-in and I have [publish the first release](https://github.com/lindehoff/Indigo-Verisure/releases).

**Comment by persandstrom** [comment]
Nice!
