### ISSUE TITLE
Feature: pull historical data

### ISSUE THREAD

**Issue by Risca** [persandstrom/python-verisure#28]
It would be a nice feature to be able to pull older measurements from a verisure device, for those times when your server is down and you miss out on a few measurements.

**Comment by persandstrom** [comment]
That would be a nice addition.
For the climate devices it might be possible to get the graph data. And for other devices there is the event list.

**Comment by persandstrom** [comment]
Is the event list something you are interested in as well, or can I close this issue?

I don't have a lot of time to spare right now so it might take a while before I start looking at the event list...

**Comment by Risca** [comment]
You can close the issue.

**Comment by persandstrom** [comment]
PR #33 has added the possibility to get event log as well
