### ISSUE TITLE
Support multiple alarm systems

### ISSUE THREAD

**Issue by palloberg** [persandstrom/python-verisure#38]
Would it be possible to support multiple systems/installations on the same login? 

The Verisure pages seems to choose the current system by adding "?inst=N" to the start.html URL where N is the installation number starting from 1.

I tested changing URL_START in session.py to include "?inst=N" and that gave me data from the correct system.  Having the ability to control this from the API and the command line would be very nice.

Getting the name of the system/installation seems a bit harder. From what I can tell the installation name  seems to be found in the HTML of start.html only so it would have to be parsed from there. For reference, 
here is the piece of HTML where it is found:

``` html
<li class="compound-navigation-list-item">
    <div class="compound-navigation-item">
        <button type="button" class="compound-navigation-item--button">
            <img src="/img/icon/not_ok.png" class="global-navigation-item--icon">
            <span class="global-navigation-item--text">Main apartment</span>                    
            <img src="/img/Common/arrow_expand.png" alt="" class="global-navigation-item--icon">
        </button>
        <div class="compound-navigation-item--sub-content-cassette">
            <div class="compound-navigation-item--sub-content-container">
<ul>
        <li class="">
            <a href="start.html?inst=1">
                Main apartment
            </a>
        </li>

        <li class="">
            <a href="start.html?inst=2">
                Second apartment
            </a>
        </li>
</ul>
        </div>
    </div>
</div>
</li>
```

**Comment by persandstrom** [comment]
I have created a branch called multiple_systems. It should be possible to select system by using the ``` -i ``` flag 
``` python verisure.py username password -i 2 get alarm ```
Could you try this and see if it works as expected? I don't have multiple systems myself. 

Would it be best to add a new command to get the system names?
``` python verisure.py username password get systems ``` 
That returns a list of inst numbers and inst names?

**Comment by persandstrom** [comment]
@palloberg were you able to test it?

**Comment by persandstrom** [comment]
Should work now
