### ISSUE TITLE
Error when Verisure is down for maintenance

### ISSUE THREAD

**Issue by lindehoff** [persandstrom/python-verisure#4]
When MyPage is down for maintenance you get the following error: 
```
Traceback (most recent call last):
  File "verisure.py", line 119, in <module>
    with MyPages(args.username, args.password) as verisure:
  File "/verisure/mypages.py", line 103, in __enter__
    self.login()
  File "/verisure/mypages.py", line 129, in login
    status = _json_to_dict(response.text)
  File "/verisure/mypages.py", line 285, in _json_to_dict
    return eval(UNESCAPE(json))
  File "<string>", line 1
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    ^
SyntaxError: invalid syntax
```

**Comment by HebronNor** [comment]
Here is a list of errors that have occurred on MyPage since October 1st.
[Verisure-logs.txt](https://github.com/persandstrom/python-verisure/files/41660/Verisure-logs.txt)

**Comment by persandstrom** [comment]
@lindehoff Thanks, I'll fix that. 

@hebronnor how have you made these logs?  Is python-verisure involved and could cause the issue

**Comment by HebronNor** [comment]
They are exported from a uptime service (uptime robot). python-verisure is
not involved,  in my experience it is usually a quick code push.

**Comment by persandstrom** [comment]
I think this is solved. 
Instead of the previous unreadable error you should get a LoginError with the message "Login failed, myPages might be down".

**Comment by HebronNor** [comment]
Will this happen with the timeout error that I saw when testing the lock integration?

**Comment by persandstrom** [comment]
No, maybe I should take the time to go through all calls to the server. 
The drawback in catching errors and replacing them with readable ones is that I loose the original information needed to fix bugs. So I'm a bit torn here.

**Comment by HebronNor** [comment]
`--debug` flag maybe? :)

**Comment by persandstrom** [comment]
Yeah, why not. That might be good for the CLI.

**Comment by HebronNor** [comment]
You could add the option of something like `myPages.debug(true)` or something like that if the user explicitly wants the exception, or for testing purposes :)

**Comment by persandstrom** [comment]
@lindehoff I noticed that you had forked and added some additional error handling. Please create a PR when you are done :)

**Comment by lindehoff** [comment]
Almost ready, will PR soon.

**Comment by persandstrom** [comment]
PR Merged, closing issue
