### ISSUE TITLE
Timeout might be too low

### ISSUE THREAD

**Issue by wencevdm** [persandstrom/python-verisure#40]
The mypages webapp tends to be slow from time to time and thus the timeout of 3 seconds is often exceeded, resulting in errors. I've raised it to 10 on my system by editing the session.py and all works fine now.

**Comment by persandstrom** [comment]
Ok, I havn't noticed this but I don't see any drawbacks on having a little longer timeout

**Comment by lindehoff** [comment]
I have noticed the same problem

**Comment by persandstrom** [comment]
The timeout is now 10s
