### ISSUE TITLE
InsecurePlatformWarning: A true SSLContext object is not available.

### ISSUE THREAD

**Issue by HyperDevil** [persandstrom/python-verisure#42]
vsure user@domain.net password get alarm

Generates this error:
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

The data is still outputted correctly though..

Ubuntu 14.04 LTS

**Comment by persandstrom** [comment]
I found a post on stackoverflow and it solved the problem on ubuntu 14.04 for me. 

http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent

```
sudo apt-get install libffi-dev libssl-dev
pip install pyopenssl ndg-httpsclient pyasn1
```
