### ISSUE TITLE
Error in setup.py for branch app_api

### ISSUE THREAD

**Issue by tcastberg** [persandstrom/python-verisure#50]
# pip install git+https://github.com/persandstrom/python-verisure.git@app_api
Collecting git+https://github.com/persandstrom/python-verisure.git@app_api
  Cloning https://github.com/persandstrom/python-verisure.git (to app_api) to /tmp/pip-Ud7hn7-build
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/vsure.egg-info
    writing requirements to pip-egg-info/vsure.egg-info/requires.txt
    writing pip-egg-info/vsure.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/vsure.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/vsure.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/vsure.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/vsure.egg-info/SOURCES.txt'
    error: package directory 'verisure/devices' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Ud7hn7-build/

**Comment by persandstrom** [comment]
Should be fixed now, please try again

**Comment by tcastberg** [comment]
Works now. :)
