### ISSUE TITLE
vacationmode missing

### ISSUE THREAD

**Issue by TheLion** [persandstrom/python-verisure#53]
Hi,

You really did a great job with the app_api implementation. Works great!

I just found out the vacationmode status is missing in the app_api overview.

Any change of implementing that?

Regards,

Martijn

**Comment by persandstrom** [comment]
Vacationmode is added in a new function in PR #54.

**Comment by TheLion** [comment]
Great!

**Comment by TheLion** [comment]
Erhm vacationmode only returns

{}

Nothing more.

**Comment by persandstrom** [comment]
That is because you dont have vacation mode set ☺

**Comment by TheLion** [comment]
Oh. Ok. So what is different than the old API. With that a value was always returned.

I can work with that.

**Comment by TheLion** [comment]
What does the first 'active': False stand for?

`{'active': False,
 'cid': '01026506',
 'fromDate': '2017-01-15T09:00:00.000Z',
 'temporaryContactName': '',
 'temporaryContactPhone': '',
 'toDate': '2017-01-15T21:00:00.000Z',
 'turnOffPetImmunity': False}
`
Shouldn't that be true?

**Comment by persandstrom** [comment]
I don't know, seems like it should be true looking at the date and times. Maybe the alarm has to be armed as well?

**Comment by TheLion** [comment]
It looks like it took some time to switch to true. Very strange,

Thanks for implementing it though! :-)
