### ISSUE TITLE
Doorlock status

### ISSUE THREAD

**Issue by hanspnyholm** [persandstrom/python-verisure#55]
No more possible to see doorlock status anymore?
A example of this would be great.

**Comment by persandstrom** [comment]
It should be included in the overview command
```vsure user@example.com mypassword overview```

Do you see it there?

**Comment by hanspnyholm** [comment]
Yes.
A exampel how to sort that info out should be great.
And how to lock the door.

**Comment by persandstrom** [comment]
I have added two new example

**Comment by hanspnyholm** [comment]
When you send the lock command when its already locked you get a error message.
Its the same the other way to.

Traceback (most recent call last):
  File "/usr/local/bin/vsure", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/verisure/__main__.py", line 225, in main
    args.new_status))
  File "/usr/local/lib/python2.7/dist-packages/verisure/session.py", line 315, in set_lock_state
    _validate_response(response)
  File "/usr/local/lib/python2.7/dist-packages/verisure/session.py", line 46, in _validate_response
    response.text.encode('utf-8')))
verisure.session.ResponseError: Invalid response, status code: 400 - Data: {"errorGroup":"BAD_REQUEST","errorCode":"VAL_00819","errorMessage":"The requested doorlock state is not possible to apply due to state already set"}

**Comment by persandstrom** [comment]
Thanks for the input, should be solved now
