### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xc5' in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by JonasStenmarck** [persandstrom/python-verisure#56]
Hi I just realised when my wife have been the last to unarm the door, vesue can´t encode right. Her name is "Åsa" ;)  
Is this due to my system or is this Ure code? (Awsome by the way!) I tried to fiddle with the locale and LANG variable.

$ vsure e-mail password armstate
{'changedVia': 'CODE',
 'cid': '12345678',
 'date': '2017-02-09T17:41:14.000Z',
 'name': Traceback (most recent call last):
.
.
.
UnicodeEncodeError: 'ascii' codec can't encode character '\xc5' in position 1: ordinal not in range(128)

**Comment by persandstrom** [comment]
Hi!
A simple test (if you are on a linux system) to see if 'Å' is a supported character  is to type ```Å``` and press enter. If the respons is ```Å: command not found``` then it works. If it sais ```\xc5: command not found``` then there is something wrong with the locale.

**Comment by JonasStenmarck** [comment]
Of corse, Python use LC_ALL that solved it ;) -Thanx!
