### ISSUE TITLE
Error XBN Database

### ISSUE THREAD

**Issue by mattiasol** [persandstrom/python-verisure#59]
verisure.session.ResponseError: Invalid response, status code: 503 - Data: {"errorGroup":"SERVICE_UNAVAILABLE","errorCode":"SYS_00004","errorMessage":"XBN Database is not activated"}
I've got his error messages the last 2 days when i try to connect to verisure.

**Comment by persandstrom** [comment]
Have you updated to the latest version. This was reported in #58 an fixed in version 1.1.2

**Comment by mattiasol** [comment]
Solved, missed the #58 issue report :(
