### ISSUE TITLE
Historical climate data

### ISSUE THREAD

**Issue by tcastberg** [persandstrom/python-verisure#60]
Hi Per,

Is it possible to use use the app api to fetch older climate data? Looking at the website I'm able to look at data back to the installation of the system, however using the vsure command I'm only getting back to about 30 days.

Cheers,
Tor Magnus

**Comment by tcastberg** [comment]
Looking at the app the data only seems to go back 30 days, while on the website it goes all the way back. Could be a limitation in the app api?

**Comment by persandstrom** [comment]
Yes, seems like it is a limitation of the app api.

**Comment by MagBuchSB1** [comment]
Hi. No update on the API to get older climate data? Where on the website can you se older data?
