### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by tnemrap** [persandstrom/python-verisure#62]
I have updated to last version.
In the version i used before i captured and used this details from eventlog "The SmartLock Huvudentre has been unlocked from the inside"
Now i can not find this information.

/Mike

**Comment by persandstrom** [comment]
You are correct, that is missing since the move to use the app-api. 
It's on the to-do list.

**Comment by tnemrap** [comment]
It would then be nice to have -f LOCK UNLOCK in the event log.

**Comment by persandstrom** [comment]
I have added the filter options in #66, release  v1.3.1

**Comment by tnemrap** [comment]
How do i get the details from eventlog according to first post in this issue.

**Comment by persandstrom** [comment]
Ah, maybe I closed the issue to fast. 
Is your goal is to capture details, like user, area etc., or do you want the long text?
