### ISSUE TITLE
Set on/off motion detector for smart cams

### ISSUE THREAD

**Issue by daweedm** [persandstrom/python-verisure#65]
Hello, is it possible to set on/off motion detector for smart cams ?

Thanks !

**Comment by persandstrom** [comment]
Hi,
No, can you do it from the app?

**Comment by DaweedM** [comment]
Hi,
Yes, we have a "my cameras" section where there is a motion detector switch for each of them

**Comment by DaweedM** [comment]
![img_0486](https://cloud.githubusercontent.com/assets/8097216/24011217/6a39f080-0a7a-11e7-95cd-3b76a52f2579.PNG)

**Comment by persandstrom** [comment]
I don't have any cameras myself, so I can't help to reverse engineer it. But it should be possible.

**Comment by DaweedM** [comment]
What tools did you use to spoof the API routes called by the app from the phone ? I could try to do it myself

**Comment by persandstrom** [comment]
I have used Charles [https://www.charlesproxy.com](url).

You can set a proxy on the wireless connection on your phone and point it to the IP of the computer running charles. You have to enable ssl ploxying in charles as well for the locations e-api02.verisure.com, mymobile.verisure.com, e-api01.verisure.com and sstats.securitas-direct.com

**Comment by daweedm** [comment]
Thanks for your advices,
I'd have liked to contribute to this project but my Python knowledge is limited.
If someone faces the same needs, I've done it with PHP : [daweedm/php-verisure](https://github.com/daweedm/php-verisure)
