### ISSUE TITLE
Invalid response - Service unavailable

### ISSUE THREAD

**Issue by Jacobh2** [persandstrom/python-verisure#67]
Hi!

First of: Very nice API! I've been using it a lot!

Since yesterday I've had some problems connecting however, and I thought that you might be able to help me shine some more light on the issue.

Both connecting from within python and from a terminal, I get this error:
`verisure.session.ResponseError: Invalid response, status code: 503 - Data: b'{"errorGroup":"SERVICE_UNAVAILABLE","errorCode":"SYS_00004","errorMessage":"XBN Database is not activated"}'`

Do you have any ideas of why I'm getting these? Am I doing something wrong?

I also have Verisure's official app, and from that one I can get all the history, statuses and change the state of a door. 

I've tested with both vsure version 1.3.0 and also 1.3.1.

Thanks for all the help!

**Comment by persandstrom** [comment]
Hi!

Verisure seem to alternate between two servers, I will try to fix this as soon as possible. 

I will fix this as soon as possible

**Comment by Jacobh2** [comment]
Just a quick follow-up question: Where have you found the Verisure API information?

**Comment by persandstrom** [comment]
I have reversed engineered it, with some guidance from @lindehoff 
The tool we have used is [www.charlesproxy.com](url)

**Comment by tomhur** [comment]
It looks like DNS e-api.verisure.com work. That is a CNAME that now points to e-api02.verisure.com

**Comment by persandstrom** [comment]
@tomhur Thanks! you saved me some time. An update will come within minutes

**Comment by persandstrom** [comment]
Version 1.3.2 released, issue solved

**Comment by magnushasselquist** [comment]
1.3.2 gives me this error still..

**Comment by persandstrom** [comment]
@magnushasselquist Seems like the issue is back, I will try to figure out a more solid solution to this

**Comment by persandstrom** [comment]
#70 should have solved the issue
