### ISSUE TITLE
Question: Response from Lock and Unlock

### ISSUE THREAD

**Issue by magnushasselquist** [persandstrom/python-verisure#71]
For Door-lock, when Locked or Unlocked the response is (examples):

Successful:
{u'doorLockStateChangeTransactionId': u'20051143'}
Failed:
{u'doorLockStateChangeTransactionId': u'34852458'}

Where can I find information about if this is actually successful or failed. Before we moved to API, the response included ok or not-ok. Can I track the TransactionID somewhere in API? History events have longer IDs..

**Comment by persandstrom** [comment]
Using the python module there is a function ```get_lock_state_transaction``` that takes a trasaction id as input and it will return the status of the door lock operation. 

The command line should probably work as an synchronus call and return the result after the transaction is done, not after the call to lock is done.
