### ISSUE TITLE
Responses to and timeouts for requests

### ISSUE THREAD

**Issue by krambriw** [persandstrom/python-verisure#76]
Hello,
First of all, thank you for this very nice library! It works great, since yesterday I am using it successfully with EventGhost and Node-RED.
During a couple of years I have had my own "homebrewed" solution using the web api but your library is much easier and better.
I modified some minors in your settings.py. For some methods using requests I have added
- timeout as parameter
- http responses

This helps when integrating with other softwares, giving feedback of successful/unsuccessful calls
(typically you want 200 as response to http calls) so you can take action, like re-transmissions etc
The timeout prevents requests to hang if the host is unavailable (I do not know if you already handle all this somehow in your code). As example, the modified method "set_smartplug_state" below. If you want the user to be able to set the timeout as a parameter, it would also be easy to add that as an argument. Just a suggestion.

Kind regards, Walter

`    def set_smartplug_state(self, device_label, state):
        """ Turn on or off smartplug

        Args:
            device_label (str): Smartplug device label
            state (boolean): new status, 'True' or 'False'
        """
        response = None
        try:
            response = requests.post(
                urls.smartplug(self._giid),
                headers={
                    'Content-Type': 'application/json',
                    'Cookie': 'vid={}'.format(self._vid)},
                data=json.dumps([{
                    "deviceLabel": device_label,
                    "state": state}]),
                timeout=5)
            return response
        except requests.exceptions.RequestException as ex:
            raise RequestError(ex)
        _validate_response(response)

`

**Comment by persandstrom** [comment]
Hi! 

You will get an indication if the call was successful or not, the ```_validate_response``` functions does that. 
If the call did not succeed a ```ResponseError``` will be raised, this exception has a ```status_code``` and a ```text``` field.

I would expect a ```RequestError``` to be raised if the host is unavailable, but for other cases where a connection is established and the server hangs for some reason I timeout might be a good idea. I'll add that.

**Comment by krambriw** [comment]
Hello Per, fine, I understand what you are saying and the _validate_response is doing what you say. However. at least in my case, I wan't the responses to be delivered to my application in all situations, even if they are just confirming a successful request. So my modified function for the smartplug looks like this, always returning the response to my other application(s)

Kind regards, Walter
 
` def set_smartplug_state(self, device_label, state):
""" Turn on or off smartplug

    Args:
        device_label (str): Smartplug device label
        state (boolean): new status, 'True' or 'False'
    """
    response = None
    try:
        response = requests.post(
            urls.smartplug(self._giid),
            headers={
                'Content-Type': 'application/json',
                'Cookie': 'vid={}'.format(self._vid)},
            data=json.dumps([{
                "deviceLabel": device_label,
                "state": state}]),
            timeout=5)
    except requests.exceptions.RequestException as ex:
        raise RequestError(ex)
    _validate_response(response)
    return response.status_code
`
