### ISSUE TITLE
Checking the panel network connection status 

### ISSUE THREAD

**Issue by krambriw** [persandstrom/python-verisure#80]
Hello Per,
Did you ever find out how it could be possible to initiate the check if the panel is on-line or off-line? (In Swedish it is named "Bredband:Online/Offline)

In some cases it could be preferable to know the status before sending commands since it will cost sms's if the panel is offline

Kind regards, Walter

**Comment by krambriw** [comment]
...and also for pure monitoring purposes

(I know you can get the latest known status via the get_overview() but I would like to refresh the status to the actual time when requested

**Comment by persandstrom** [comment]
That should be quite easy to add,

I can take a look at it soon

**Comment by persandstrom** [comment]
There is a new command now, ```test_ethernet```. It will update the ethernet status. I don't know how long it takes after the command is sent before the status is updated.

**Comment by krambriw** [comment]
Thank you very much Per!
It looks great, I have implemented the test control in my python script so it is running now. Next is to test what happens when I disconnect/connect the verisure panel from network (the detection time online/offline will depend on how frequent I request the update, normally the status check takes around 1-2 seconds when using the app)
