### ISSUE TITLE
HeatPumps

### ISSUE THREAD

**Issue by jamiewalters** [persandstrom/python-verisure#81]
I am interested in adding support for HeatPumps (get status, change temperature, etc)

They show up in the /overview as:

 "heatPumps": [
        {
            "deviceLabel": "XXX XXX",
        },
            "heatPumpModel": "PANASONIC",
            "heatPumpConfig": {
                "status": "RUNNING",
                "mode": "HEAT",
                "power": "ON",
                "targetTemperature": 21,
                "fanSpeed": "LOW",
                "airSwingDirection": {
                    "vertical": "0_DEGREES"
                },
                "feature": "QUIET",
                "changedTime": "2017-09-27T22:12:48.647Z"
            }
        }
    ],

However from there I haven't managed to work out the resource for fetching only the heatpump or to post updates to it.

This could be done with the regular "mypages" There you could send the payload as a post request. First choice however would be to keep it all on the same URL and session.

Any tips on going forward?

**Comment by persandstrom** [comment]
Hi,
Is it possible to do this from the app?

**Comment by jamiewalters** [comment]
Exactly, you can control all the function of the heatpump from the apps.

**Comment by persandstrom** [comment]
Then It should be doable. I don't have a heatpump myself so you have to add the functionality yourself. 

I have installed https://www.charlesproxy.com on a computer used it as a reverse proxy for my cell phone. When ask certificate is exchanged it is possible to sniff the traffic from the app.

**Comment by jamiewalters** [comment]
I managed to added HeatPumps, tested at home, works as expected. However the interface for the HeatPump has a few more options. I opted for a single function that takes (property, state) with property freely being any given property of the HeatPump. Given that I would like to contribute this code, is there a preferred style?

**Comment by persandstrom** [comment]
Great! If you create a pull request I can take a look at it.

**Comment by taugusti** [comment]
Hi @persandstrom  and @jamiewalters 
I am also hoping to find heat pump support... It seems like Jamie got i running - but it does not appear to be a part of the main line.
Is there any plan to add it - or perhaps I could get a copy of the prototype to see if I can make it work?

**Comment by jamiewalters** [comment]
Hi @taugusti  I got it running at home but I have been quite busy to merge it with the latest code and push it back. I am more than happy to share this, maybe you can add some input to make it more useable before merging.

-Jamie

**Comment by taugusti** [comment]
Great - how do I get access to it? can you mail it (or  link to it): thomas at augustinus dot dk?
Btw. I got the existing version up and running and now have the staus of the heatpump in my Home Assistant setup. But adding "change settings" would be great. It is a great module @persandstrom.

**Comment by jamiewalters** [comment]
https://github.com/jamiewalters/python-verisure

**Comment by jamiewalters** [comment]
I am working on a HASS climate component to go with this, let me know if you are interested in testing it.

**Comment by taugusti** [comment]
Hi @jamiewalters, I have only had limited time to test - and I seem to recall that I could test by executing the scripts from the ssh console or on my pc... but I can't do that anymore because of a missing reference. I will look at it later.
I made an extra python script to wrap the other one - that handles initiating the session, getting/setting and then closing the session. It is my first attempt at setting parameters with input_select. It seems that the script is not called when I change values. The same when I try to make the selector reflect the current state. I must be doing something totally wrong :-)
Are you doing it the same way? or is there an easier way to go?
Btw - since you are using hass - could you show me the scripts/config you use to present it ?

And yes - I would love to help test the climate component!

**Comment by taugusti** [comment]
Hmm - I need to look into it again. Did you install any extra libraries?
It would be great to see your config - thanks!

**Comment by jamiewalters** [comment]
try this:

https://github.com/jamiewalters/python-verisure-climate

still very rough, first hass component, will keep improving it in the coming days. since hass defaults to v 1.3.7 of vsure I add it beside the component and reference it locally.

**Comment by follox** [comment]
Hi @jamiewalters 
Thanks a lot for this. I was posting a feature request on the forum to ask if someone could update the Home Assistant component. Will check this out tonight :)

**Comment by jamiewalters** [comment]
Let me know how it works, I am only aware of it being tested on two HeatPumps, I am not certain all the options are the same for every pump but let me know, so it can up updated.

**Comment by follox** [comment]
@jamiewalters It works like a sharm! Thanks a lot. But it is only showing one of two pumps. Anything I can do to fix that?

**Comment by jamiewalters** [comment]
Let me look at the code again, never been tested in multiple pumps as I only have one :/ Can you open an issue at my repo?

**Comment by follox** [comment]
If any help it is this heatpump:
Panasonic HZ9 RKE-1

**Comment by jamiewalters** [comment]
Try the latest commit - J

**Comment by jamiewalters** [comment]
The python lib supports setting these, just never figured out how to add them to home assistant.

**Comment by follox** [comment]
I hope someone can also integreate power consumption and also the two missing modes. You can also just adjust swing mode vertically but not horizontally.

**Comment by jamiewalters** [comment]
I did the support for adjusting swing mode, I didn't have any horizontal adjustments to test with so I couldn't add support for horizontal, maybe you can send me an example of your overview data from the python lib. I will look into the power consumption. The modes are in the python lib, I just dont know where they would fit into the climate component, Ill look into this.

**Comment by follox** [comment]
Hi again. Much appreciated. 
Where do you want me to send\upload the overview data for the python lib?

**Comment by jamiewalters** [comment]
Open an issue here: https://github.com/jamiewalters/python-verisure-climate
and share the file, scrub all sensitive data, I only need to see what they heatPumps config looks like

**Comment by follox** [comment]
Alright, I will do that tonight. Can't access samba from work.
You want the details in my verisureclimate.py file, right?

**Comment by follox** [comment]
I am not sure what file you want me to gather information from.

**Comment by jamiewalters** [comment]
No, I wanted to see what the output from your versure data is like, you would have to run python-versire lib and print it out.

**Comment by follox** [comment]
@jamiewalters
I do not have any file with that name extension in the folder.

**Comment by follox** [comment]
@jamiewalters ?

**Comment by jamiewalters** [comment]
I am trying to get a copy of your output from Verisure when the module is running. You can get this by running, this lib here python-verisure and doing get_overview() this should return this data.

**Comment by follox** [comment]
I am sorry, but I am unable to write python. 
Will need some explanation about how I can proceed with this. What should I write in this python file in order to retrieve the data you asking for?

Maybe some text I can copy paste?

**Comment by follox** [comment]
@jamiewalters Sorry to bother you with this, but can you please give me a detailed text or a recipe on how to proceed? Thanks :)

**Comment by turbokongen** [comment]
@follox look at the readme of this project.

**Comment by jamiewalters** [comment]
Hi

Not an issue, I just don't find the time to answer so quickly. Check the readme as said above its a good way to begin, the method you need to call is "get_overview()"

**Comment by follox** [comment]
The readme does not say anything about this.
https://github.com/jamiewalters/python-verisure-climate/blob/master/README.md

**Comment by persandstrom** [comment]
@jamiewalters I have updated vsure in HA to version 1.5.0

**Comment by jamiewalters** [comment]
Excellent, I have a component for adding the heatpumps as a climate device, how could we get this in?

**Comment by persandstrom** [comment]
I think the best way is to read to docs on how to sSubmit your work]
[https://developers.home-assistant.io/docs/en/development_submitting.html) to home assistant.
When you have created a PR I can help out to review it.

**Comment by follox** [comment]
Hi @jamiewalters 
It seems like the verisure plugin for HomeAssistant has stopped after upgrading to the newest version. 
Can you check into this?

```
Integrations need to be in their own folder. Change climate/verisureclimate.py to verisureclimate/climate.py. This will stop working soon
```

If I move it to a new folder it does not work eiter...

**Comment by jamiewalters** [comment]
Will check this out

**Comment by taugusti** [comment]
@jamiewalters - any news on this?
Anything I can do to help?

**Comment by taugusti** [comment]
I have added an issue in the repository here: 
https://github.com/jamiewalters/python-verisure-climate/issues/4

**Comment by follox** [comment]
@taugusti Thanks for looking into this as well. 
Is there any way to integrate the climate into the Verisure component?
https://www.home-assistant.io/components/verisure/

The heatpump sensor is a part of Verisure, so a bit unsure why it is not included in the component.

**Comment by taugusti** [comment]
Hi @follox 
I fixed the issue and made a pull-request for @jamiewalters.
When he has reviewed and approved it, you can get it from his repository.

If you want to get moving and help test it, you can get it here: [](https://github.com/taugusti/python-verisure-climate/tree/patch-1)

Regarding including it into the climate component... I guess we should give it a try... I assume there is a formal procedure for adding to home assistant... Maybe you could research it?

**Comment by follox** [comment]
@taugusti Well, I do not know anything about this. 
But I guess we can upload a hvac.yaml file here:
https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/verisure

This is the yaml files the Versiure component is using.

**Comment by jamiewalters** [comment]
I have merged this request in the repo.

**Comment by jamiewalters** [comment]
I would like to get it added to Hass however I have not been able to commit much time to doing this. But it would be a better approach and use the same Verisure instance used for the other Verisure components.

**Comment by follox** [comment]
Alright, I got it to work. Thanks for that! But hass.io is complaining with the following:
Your configuration contains extra key that the platform does not support (but were silently acceptet before 0.88). Please find and remove the followin. This will become a breaking change.

[uername], [password] Line 109

I am using the Verisure component as well so the configuration looks like this:
verisure:
username: xxxx
password: !secret verisure_pw
locks: 1
smartplugs: 1
alarm: 1
hygrometers: 1
thermometers: 1
door_window: 1

Then line 109:
climate:
- platform: verisureclimate
username: xxxx
password: !secret verisure_pw

**Comment by jamiewalters** [comment]
I am not so familiar with the recent changes that causes this to happen.  I am working on a pull request to add this to the built in verisure component, almost done.

**Comment by jamiewalters** [comment]
Component added this to Home Assistant upstream, awaiting a review. @persandstrom perhaps you can help with this?

**Comment by persandstrom** [comment]
@jamiewalters I added some comments, if you need any help please ask and I can support.

**Comment by follox** [comment]
Hello. I was just wondering whether the Verisure component is updated or not?

**Comment by follox** [comment]
@jamiewalters ?

**Comment by jamiewalters** [comment]
Hey I haven't updated the pull request as yet, been offline a while.

**Comment by follox** [comment]
@jamiewalters Can you please follow up the request here?
https://github.com/home-assistant/home-assistant/pull/22555

Cheers

**Comment by follox** [comment]
@persandstrom Is this something you can look into?

**Comment by persandstrom** [comment]
@follox No, I don't have a heat pump. It is better this is done by someone who has the hardware. @jamiewalters if you need any support I am happy to help out.

**Comment by jamiewalters** [comment]
There were a few stuff to be fixed, some quicker than others. I am working through the list as time and knowledge permits.

**Comment by follox** [comment]
@jamiewalters Since nothing has happen they closed your ticket.
How should we go about this? Do you need to go back to start again?

![image](https://user-images.githubusercontent.com/43533933/59488778-baa75f80-8e80-11e9-9cb7-a3df3d0380ea.png)

**Comment by follox** [comment]
@persandstrom has asked you @jamiewalters several times if you need help regarding this. Is this something he can look into for you?

**Comment by follox** [comment]
@taugusti Anything we can do about this?

**Comment by taugusti** [comment]
Hi @follox 
I wiould also love to get this integrated into hass - it is great work that @jamiewalters and @persandstrom  have done!

I do not have the time to find out how this works and can be integrated into hass at the moment... and for the next year (studying mba nex to my full time++ job) .
So - if someone does something, I can test (I have a panasonic heat pump on verisure). but more than that it not possible at the moment. If I have to do something special to be able to test a complete alpha build of hass, then I need some instructions...

I think we just have to wait for @jamiewalters to have time to work on it.

/th

**Comment by follox** [comment]
@taugusti Alright, I think this will just stop now as the case is closet. Is the heatpump working in your hass? Mine has stopped working completely.

**Comment by niro1987** [comment]
is this still a thing?

**Comment by persandstrom** [comment]
Not sure, let’s close it for now
