### ISSUE TITLE
@Home

### ISSUE THREAD

**Issue by tnemrap** [persandstrom/python-verisure#83]
Is it possible to add @Home functionality to the application?

/Mike

**Comment by persandstrom** [comment]
Can you explain what you mean by @home functionality?

**Comment by jamiewalters** [comment]
verisure has added a new feature in its map where you can tag yourself as being at home.

**Comment by persandstrom** [comment]
OK, I did not know about that. I will take a look at it and see how it can be integrated

**Comment by persandstrom** [comment]
What kind of @home functionality do you want @tnemrap ?
The overview contains a section called "userTracking".

**Comment by tnemrap** [comment]
The functionallity is To check If a under is Home or not.

/mike

**Comment by persandstrom** [comment]
That information is present in the overview. 
```userTracking.users["UserName"].currentLocationName```
