### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by howi42** [persandstrom/python-verisure#85]
After changing the password for my Verisure account, I cannot get the command line version to work anymore.
Error : 
Traceback (most recent call last):
  File "/usr/local/bin/vsure", line 11, in <module>
    load_entry_point('vsure==1.4.0', 'console_scripts', 'vsure')()
  File "/usr/local/lib/python2.7/dist-packages/verisure/__main__.py", line 210, in main
    session.login()
  File "/usr/local/lib/python2.7/dist-packages/verisure/session.py", line 90, in login
    self._vid = json.loads(response.text)['cookie']
KeyError: 'cookie'

**Comment by persandstrom** [comment]
I tried to change my own password and everything works fine after that. Are you using any special characters in your new password that might cause this? try to set a password with only a-z,A-Z,0-9 and see if that works.

**Comment by howi42** [comment]
You are right, it does work today, regardless the characters used.
Not sure what happened, since I did not change anything since yesterday.
But thank you for your help.
