### ISSUE TITLE
Errors in verisure :(

### ISSUE THREAD

**Issue by Nitrosito** [persandstrom/python-verisure#88]
I have HomeAssistant 0.55.2

I config verisure:
verisure:
  username: !secret verisure_username
  password: !secret verisure_password

And get this errors
```
2017-10-17 20:14:54 ERROR (MainThread) [homeassistant.setup] Error during setup of component verisure
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 194, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/homeassistant/components/verisure.py", line 69, in setup
    if not HUB.login():
  File "/usr/src/app/homeassistant/components/verisure.py", line 119, in login
    self.session.login()
  File "/usr/local/lib/python3.6/site-packages/verisure/session.py", line 90, in login
    self._vid = json.loads(response.text)['cookie']
KeyError: 'cookie'
```

Any idea? Im from spain
thanks!

**Comment by persandstrom** [comment]
The Spanish Verisure system is not supported by python-verisure. I have no idea how different it is and if it would be possible to add support.

**Comment by Nitrosito** [comment]
wow, bad notice D:
I try read the code and try to fix this.

Thanks and regards

**Comment by howi42** [comment]
I have the same error with the Verisure modul, this time in Norway.
There is a bell ringing in my head regarding the cookie stuff, but I don't remember it anymore.
Any ideas ?

**Comment by howi42** [comment]
Just some more info : I get this error now in all installations ( both python 2 and 3 )

**Comment by howi42** [comment]
hhhmm,   noting changed, but it works again.
Probably a Verisure hickup.

**Comment by persandstrom** [comment]
Seems like there has been some problems at Verisure this night.

**Comment by mvillarejo** [comment]
Wondering if you've done some progress in verisure integration for Spanish version... (Puedo intentar ayudar)

**Comment by persandstrom** [comment]
@mvillarejo No, I don't know how much the Spanish Verisure system differs from the Scandinavian. Someone with the Spanish App and knowledge has to figure it out.

**Comment by mvillarejo** [comment]
@Nitrosito maybe we can work together?

**Comment by Nitrosito** [comment]
@mvillarejo I'm sorry I'm not so interested in integrating verisure

**Comment by efpe** [comment]
It looks like the Spanish verisure app is using a different way of communicating. 

The request from the app looks like this:

```
Host:             mob2217.securitasdirect.es:12010
Accept:           */*
Cookie:           JSESSIONID=xxxx
User-Agent:       Verisure/5 CFNetwork/901.1 Darwin/17.6.0
Accept-Language:  en-gb
Accept-Encoding:  br, gzip, deflate
Connection:       keep-alive
```

They do some authentication the first time you log in and then you use `JSESSIONID` and the a `hash` parameter in the query string when sending further requests.

Reponse looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<PET>
  <RES>OK</RES>
  <STATUS>0</STATUS>
  <MSG>Your Alarm is deactivated</MSG>
  <NUMINST>xxx</NUMINST>
  <BLOQ remotereqactive="1" >Estamos mejorando nuestros servicios. Por favor intentelo de nuevo mas tarde. Gracias por confiar en Securitas Direct</BLOQ>
</PET>
```

I think the integration is doable, however I will not have time to do it.

**Comment by befiware** [comment]
I'm new with Home Assistant and trying to setup Verisure integration. I'm from Finland, so this should be work for me but got this kind of errors:

1) Setup failed for verisure: Component failed to initialize.
2) Could not log in to verisure, HTTPSConnectionPool(host='e-api01.verisure.com', port=443): Max retries exceeded with url: /xbn/2/cookie (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f01ab52d278>: Failed to establish a new connection: [Errno -3] Try again',))

I can log in with my credentials to Verisure My Pages. Current HA version is 0.82.0

Any ideas what to try next?

**Comment by saksholm** [comment]
I'm new with Home Assistant and trying to setup Verisure integration. I'm from Finland, so this should be work for me but got this kind of errors:

1) Setup failed for verisure: Component failed to initialize.
2) Could not log in to verisure, HTTPSConnectionPool(host='e-api01.verisure.com', port=443): Max retries exceeded with url: /xbn/2/cookie (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f01ab52d278>: Failed to establish a new connection: [Errno -3] Try again',))
I can log in with my credentials to Verisure My Pages. Current HA version is 0.82.0

Any ideas what to try next?

**Comment by titoudoc** [comment]
> I think the integration is doable, however I will not have time to do it. The client needs to handle retries that is one thing I saw from the dump.

By any chances, could you manage to do the integration ? Thanks.

**Comment by efpe** [comment]
> > I think the integration is doable, however I will not have time to do it. The client needs to handle retries that is one thing I saw from the dump.
> 
> By any chances, could you manage to do the integration ? Thanks.

No, unfortunately I don't have time to do this at least for now.

**Comment by Cebeerre** [comment]
> It looks like the Spanish verisure app is using a different way of communicating.
> 
> The request from the app looks like this:
> 
> ```
> Host:             mob2217.securitasdirect.es:12010
> Accept:           */*
> Cookie:           JSESSIONID=xxxx
> User-Agent:       Verisure/5 CFNetwork/901.1 Darwin/17.6.0
> Accept-Language:  en-gb
> Accept-Encoding:  br, gzip, deflate
> Connection:       keep-alive
> ```
> 
> They do some authentication the first time you log in and then you use `JSESSIONID` and the a `hash` parameter in the query string when sending further requests.
> 
> Reponse looks like this:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <PET>
>   <RES>OK</RES>
>   <STATUS>0</STATUS>
>   <MSG>Your Alarm is deactivated</MSG>
>   <NUMINST>xxx</NUMINST>
>   <BLOQ remotereqactive="1" >Estamos mejorando nuestros servicios. Por favor intentelo de nuevo mas tarde. Gracias por confiar en Securitas Direct</BLOQ>
> </PET>
> ```
> 
> I think the integration is doable, however I will not have time to do it. The client needs to handle retries that is one thing I saw from the dump.



> It looks like the Spanish verisure app is using a different way of communicating.
> 
> The request from the app looks like this:
> 
> ```
> Host:             mob2217.securitasdirect.es:12010
> Accept:           */*
> Cookie:           JSESSIONID=xxxx
> User-Agent:       Verisure/5 CFNetwork/901.1 Darwin/17.6.0
> Accept-Language:  en-gb
> Accept-Encoding:  br, gzip, deflate
> Connection:       keep-alive
> ```
> 
> They do some authentication the first time you log in and then you use `JSESSIONID` and the a `hash` parameter in the query string when sending further requests.
> 
> Reponse looks like this:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <PET>
>   <RES>OK</RES>
>   <STATUS>0</STATUS>
>   <MSG>Your Alarm is deactivated</MSG>
>   <NUMINST>xxx</NUMINST>
>   <BLOQ remotereqactive="1" >Estamos mejorando nuestros servicios. Por favor intentelo de nuevo mas tarde. Gracias por confiar en Securitas Direct</BLOQ>
> </PET>
> ```
> 
> I think the integration is doable, however I will not have time to do it. The client needs to handle retries that is one thing I saw from the dump.

May I ask you how you managed to sniff the traffic ? I've tried to proxy the requests but they seem to be doing certificate pinning. I've tried as well to repackage the app with the Frida library, but then I cannot load the app. It just hangs ... 

Any help is more than welcome !

Thanks,
Xavi

**Comment by efpe** [comment]
Hey Xavi,

I used `mitmproxy` on a Mac OS and proxied the traffic through from an iPhone.

**Comment by Cebeerre** [comment]
I used the same approach, but with an Android. Maybe they are not doing the certificate pinning on IOS. Will try with an an iPhone ...

Thanks !

**Comment by krambriw** [comment]
Hello efpe,
With this method, are you able to see push messages sent to the app?

**Comment by Cebeerre** [comment]
Thanks @efpe, I finally managed to sniff the traffic with an iPhone. They do certificate pinning in Android, but they trust the user installed CAs on IOS ...

@titoudoc I've created an API Client for the Spanish accounts (might work with others that use the same API system):

[https://github.com/Cebeerre/VerisureAPIClient](VerisureAPIClient)
