### ISSUE TITLE
Support multiple alarm systems

### ISSUE THREAD

**Issue by psgandalf** [persandstrom/python-verisure#89]
Hi,
It looks as if the cli version has support for multiple alarm systems. It doesn't look like modules support it. 
Is this something that is considered in future versions?

Thanks in advance.

**Comment by persandstrom** [comment]
You can do as the cli does.
```session.set_giid(session.installations[ "installation number" ]['giid'])```
This is not a very elegant solution ...

**Comment by psgandalf** [comment]
It does all that I need. Many thanks for the fast respons and for a greate python module :+1:
