### ISSUE TITLE
Enable "with" usage

### ISSUE THREAD

**Issue by dala318** [persandstrom/python-verisure#91]
It would be helpful if the session class could be extended with __enter__ and __exit__ functions so that a simple with use case is enabled.

**Comment by persandstrom** [comment]
Good idea, don't need it myself but I would accept such a PR if you know how to implement a context manager.

**Comment by dala318** [comment]
I can push a proposal how to add such function.

**Comment by dala318** [comment]
I don't seem to have rights to push or create pull request, please advice...

**Comment by persandstrom** [comment]
You fork the project on github and push to your own repository. Then you can create a pull request from the github page. 
There is som info on how to do it [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)
