### ISSUE TITLE
XBN Database is not activated

### ISSUE THREAD

**Issue by krambriw** [persandstrom/python-verisure#93]
Hello, from time to time, I can see the following error message below. What is this? Is it something with the python-verisure module or is it simply something that is down @ Verisure?

Kind regards, Walter

`06:47:13 Time Out Invalid response, status code: 503 - Data: {"errorGroup":"SERVICE_UNAVAILABLE","errorCode":"SYS_00004","errorMessage":"XBN Database is not activated"}
`

**Comment by turbokongen** [comment]
That is when maintenance is performed on their servers. Today at 06-09:000 this could occour, and also on monday at 14:00-14:10 this happened.

**Comment by krambriw** [comment]
Oh, I see, good to know, thank you.

Most of the time my python while loop recovers automatically when this error occurs but sometimes I have to restart my python script. Do we have any recommendations how to handle exceptions like this and others. Can a python script close down it's threads and then restart itself?
