### ISSUE TITLE
Session Cache

### ISSUE THREAD

**Issue by xibriz** [persandstrom/python-verisure#95]
There seems to be some cashing issues. I will add two code snippets below.

In the first example, when I print the overview, the SmartPlug is OFF, then I turn it ON, and the second print of the overview the SmartPlug is ON.

In the second example there I don't log out between the request the SmartPlug is ON in  the overview print, then I turn it OFF, and the second print of the ovreview the SmartPlug is ON. **This sould print OFF**.

```
import verisure
import pprint

session = verisure.Session('email', 'pass')

session.login()
overview = session.get_overview()
session.logout()

pprint.pprint(overview)

session.login()
session.set_smartplug_state('serial', True)
session.logout()

session.login()
overview = session.get_overview()
session.logout()

pprint.pprint(overview)
```

```
import verisure
import pprint

session = verisure.Session('email', 'pass')

session.login()
overview = session.get_overview()

pprint.pprint(overview)

session.set_smartplug_state('serial', False)

overview = session.get_overview()
session.logout()

pprint.pprint(overview)
```

**Comment by persandstrom** [comment]
Could it be that you are too quick? I guess the overview won't change until the plug has actually switched and reported back to the Verisure servers.

**Comment by xibriz** [comment]
This is strange. I have tried adding a timestamp as a GET-parameter but it dit not work.

I have also tried adding no-cache headers:
```
"Pragma": "no-cache"
"Cache-Control": "no-cache"
"Expires": "0"
```

But the only thing that works is to log out/in.

**Comment by xibriz** [comment]
Damn... forget it. Bug in my own code 👎
