### ISSUE TITLE
Where set username and password ?

### ISSUE THREAD

**Issue by ledzepass** [persandstrom/python-verisure#97]
Sorry i'm newbie in Pyhthon. I don't find where i can set my username and password verisure ?

Bests Regards

**Comment by persandstrom** [comment]
The username and password is passed to the Session constructor. Like the example from the README
```
import verisure

session = verisure.Session('user@example.com', 'mypassword')
session.login()
armstate = session.get_arm_state()
session.logout()
print(armstate["statusType"])
```

**Comment by ledzepass** [comment]
Thanks
