### ISSUE TITLE
Get Events seams to be broken

### ISSUE THREAD

**Issue by werner81** [persandstrom/python-verisure#98]
This used to work
events = session.get_history((),1,0)

Now it returns..
{u'errorCode': u'AUT_00002', u'errorGroup': u'UNAUTHORIZED', u'errorMessage': u'REQUEST UNAUTHORIZED: GET /installation/{giid}/eventlog

I haven’t checked if the communication between Verisure APP and server has changed, but I assume something has changed in the internal API.

Br Mikael

**Comment by persandstrom** [comment]
Fixed now
